kind: ServiceAccount
apiVersion: v1
metadata:
  name: traefik
  namespace: ns1
  labels:
    app.kubernetes.io/name: traefik
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik
  namespace: ns1
  labels:
    app.kubernetes.io/name: traefik
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: traefik
  namespace: ns1
  labels:
    app.kubernetes.io/name: traefik
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: traefik
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: traefik

---