apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-binding
subjects:
- kind: ServiceAccount
  name: tiller
roleRef:
  kind: Role
  name: tiller-role
  apiGroup: rbac.authorization.k8s.io
---